### PR TITLE
Rename all isEqual methods to isEqualTo and isLessThen and isGreaterThen to isBefore and isAfter for Time

### LINKED ISSUE #285: Naming differences for `isAfter` and `isBefore`
**Describe the bug**
If found another difference in naming when it comes to `isAfter` vs `isGreaterThen` and `isAfterOrEqual` vs `isGreaterThanEq`.

I think the difference is even greater then the previous one as we have an additional `Then` and `Eq` instead of `Equal`.

**Expected behavior**

I would expect that the naming follows the same schema so that all are using the same schema.

I'd prefer `isAfter` and `isAfterOrEqual` and the same for `isBefore`.

**Additional context**

Is there a reason for the naming or is it just something that fell down before the initial release? If so, I would provide a pull request to handle it.

### PR DESCRIPTION
**Pull request by christian-kolb**
<h2>Change Log</h2> 
<div id="change-log">
  <h4>Changed</h4>
  <ul id="changed">
    <li>Renamed all isEqual methods to isEqualTo</li>
    <li>Renamed all isLessThen/isGreaterThen methods to isBefore/isAfter</li>
  </ul>  
</div>
<hr/>

<h2>Description</h2>

Resolves #285

### CODE REVIEW

**Comment by christian-kolb** [comment]
@norberttech I think I found all of them even though there where a few more than I thought.
Could you be so kind and take over the infection part again? And look over all changes? 🙂

**Comment by christian-kolb** [comment]
Apparently the infections didn't trigger. Seems the ignore annotation worked 🙂
Then I guess it's "just" review / QA and a new release if everything looks good 🙂

**Comment by norberttech** [comment]
Amazing, I will do my best to review it later this week!

**Comment by norberttech** [comment]
🎉

**Pull request merged**
