### PR TITLE
Refactor internal structure to prevent breaking tests

### LINKED ISSUE #290: Tests failing due to internal structure
**Describe the bug**

The resulting internals of a new `DateTime` object differ depending on the used method of construction. This leads to failing tests depending on how the objects are constructed.

This works:

```php
public function test_equals_works() : void
{
    $this->assertEquals(
        DateTime::fromDateTime(new \DateTimeImmutable('2022-01-01 15:00:00')),
        DateTime::fromString('2022-01-01 15:00:00')
    );
}
```

This doesn't:

```php
public function test_equals_works() : void
{
    $this->assertEquals(
        DateTime::fromDateTime(new \DateTimeImmutable('2022-01-01 15:00:00')),
        new DateTime(
            new Day(
                new Month(
                    new Year(2022),
                    1
                ),
                1
            ),
            new Time(15, 0, 0),
            TimeZone::UTC()
        )
    );
}
```

and fails with:

```txt
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 Aeon\Calendar\Gregorian\DateTime Object (
-    'day' => null
-    'time' => null
-    'timeZone' => null
-    'dateTime' => DateTimeImmutable Object (...)
+    'day' => Aeon\Calendar\Gregorian\Day Object (...)
+    'time' => Aeon\Calendar\Gregorian\Time Object (...)
+    'timeZone' => Aeon\Calendar\Gregorian\TimeZone Object (...)
+    'dateTime' => null
 )
```

**Expected behavior**

This should work:

```php
public function test_equals_works() : void
{
    $this->assertEquals(
        DateTime::fromDateTime(new \DateTimeImmutable('2022-01-01 15:00:00')),
        new DateTime(
            new Day(
                new Month(
                    new Year(2022),
                    1
                ),
                1
            ),
            new Time(15, 0, 0),
            TimeZone::UTC()
        )
    );
}
```

**Additional context**

This might also impact the `$clean` logic within the time units like month which have the same issues.

Making the state identical for all methods on construction would also remove the side effects. For example when I construct a `Time` object from a string like `15:00:00` the `hour`, `minute`, ... properties won't be set. When I then call the getter `hour()` on it, the internal state of an "immutable" object is updated and the values are suddenly available which will might then change the test result.

I don't know whether this internal behaviour was chosen because it was the faster initial setup or whether there might be a specific reason where this solution was the only one the solve a specific issue?

Can you think of a workaround for this?

### PR DESCRIPTION
**Pull request by christian-kolb**
<h2>Change Log</h2> 
<div id="change-log">
  <h4>Changed</h4>
  <ul id="changed">
    <li>Refactored internal structure of <code>Time</code>, <code>Day</code>, <code>Month</code>, <code>DateTime</code> and <code>TimeZone</code>, so that it's independent from the way it's constructed.</li>
  </ul>  
</div>
<hr/>

<h2>Description</h2>

Refactored construction and getters so that they always have the same internal state independent from the way the object is constructed. As a side effect of this refactoring, those classes are now really immutable.

Resolves #290

### CODE REVIEW

**Comment by christian-kolb** [comment]
@norberttech This PR is of course not complete. This is only a start to show how the "refactoring" would look like, what complexities it would remove and how the objects should be immutable afterwards 🙂
Does this work for you? Then I would work through this refactoring for the other time unites.

**Comment by christian-kolb** [comment]
@norberttech It wasn't as much work as I expected, so I finished the refactoring and the new test is now succeeding. I only refactored the classes that prevent this test from running through. If this works for you in general, I could supply an additional PR to do the same refactoring for the rest of the package 🙂

**Comment by christian-kolb** [comment]
@norberttech According to your feedback I switched back to deferred generation of the `\DateTimeImmutable` and `\DateTimeZone`. So the biggest change now is that the caching was lost. I think the only instance where that should lead to measurably worse performance is when thousands of transformation calls are triggered on the same object which sounds like an edge case to me. I haven't measured the impact of the previous direct initiation version, so I can't say how much faster this variant is.
I think the performance hit (if there is one) is now where it should be. The internal usage of DateTime is for validation and transformation where it makes sense to not reinvent the PHP SDK. And when getting that advantage, it's ok to have "worse performance" than when reinventing it with own code. For the other times it might be little bit slower, but on the other hand we now have less RAM need as the DateTimeImmutable objects aren't kept in cache any more. So depending on the context it might even be faster because of it 🙂

**Comment by norberttech** [comment]
Let me merge in the way you proposed it and run a few tests in a project where I'm using this library since it was where the bottleneck was detected. I will just not tag it until I confirm there is no, significant performance degradation

**Comment by christian-kolb** [comment]
Let me know if there is a performance degradation and where it is. I will then try to think about a better solution 🙂

**Pull request merged**
