### PR TITLE
Rename plus and minus to add and sub

### LINKED ISSUE #281: Different naming for mutation methods
**Describe the bug**
There is a different naming scheme when it comes to mutations of `DateTime` and `Day`.

For `Day` the methods are named `plus*` and `minus*` (for example `plusDays($days)` or `minusDays($days)`).
For `DateTime` the methods are named `add*` and `sub*` (for example `addDays($days)` or `subDays($days)`).

**Expected behavior**

I would expect that the naming follows the same schema so that both are ether using `plus/minus` or `add/sub`.

**Additional context**

I'm not sure if that's a bug or whether there is a specific reason. I looked through the documentation but couldn't find an explanation why the naming schemes are different and how I would know when to use which naming.

Is there a specific reason or just due to growth of the library and nobody noticed it until now? 🙂

**UPDATE**: I've also looked into `Time` and it only has `add/sub` without any shortcut methods. So I guess `Day` is the outlier.

### PR DESCRIPTION
**Pull request by christian-kolb**
<h2>Change Log</h2> 
<div id="change-log">
  <h4>Changed</h4>
  <ul id="changed">
    <li>Changed all methods from `plus` to `add` and `minus` to `sub`.</li>
  </ul>  
<hr/>

<h2>Description</h2>

Resolves #281

### CODE REVIEW

**Comment by christian-kolb** [comment]
@norberttech When running the tests locally with a PHP version that has the `date.timezone` `UTC` configured (I think that's the cause), the tests are randomly failing.

For example:

```
There was 1 failure:

1) Aeon\Calendar\Tests\Unit\Gregorian\DateTimeTest::test_creating_datetime_from_string with data set #25 ('2020-10-25 02:30:00+02:00', '2020-10-25 02:30:00 Europe/Warsaw', 'Y-m-d H:i:sP')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'2020-10-25 02:30:00+02:00'
+'2020-10-25 02:30:00+01:00'
```

```
There was 1 failure:

1) Aeon\Calendar\Tests\Unit\Gregorian\DateTimeTest::test_creating_datetime_from_string with data set #25 ('2020-10-25 02:30:00+02:00', '2020-10-25 02:30:00 Europe/Warsaw', 'Y-m-d H:i:sP')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'2020-10-25 02:30:00+02:00'
+'2020-10-25 02:30:00+01:00'
```

I don't think that it's related to the PR but something that should be looked into 🙂

**Comment by norberttech** [comment]
Thanks, this looks great! 
Before I merge this one, let me first try to figure out what's wrong with those failing tests since local timezone setting should not affect this test 🤔

**Comment by christian-kolb** [comment]
> Thanks, this looks great! Before I merge this one, let me first try to figure out what's wrong with those failing tests since local timezone setting should not affect this test 🤔

As they're also failing on the CI, I guess it's more because of a summer time / winter time switch where the tests aren't taking this into account. It might be better to create the dates in the timezone `UTC`. Otherwise the tests need to account for that change explicitly 🙂

**Comment by norberttech** [comment]
Unfortunately, I'm afraid it's another BC break in PHP, unrelated to the `UTC` in php.ini settings, check here: https://github.com/aeon-php/calendar/pull/283

It would not be the first one, https://github.com/aeon-php/rate-limiter is broken due to a bug in how PHP started to handle microseconds in DateInterval, it was already fixed but it looks like it will be released in 8.1.10

**Comment by christian-kolb** [comment]
So the current `8.1` release has an issue with handling DateIntervals? Good to know.
Only the mutation tests are still failing.

**Comment by norberttech** [comment]
Yeah, in 8.1 definitely rate limiter is affected but if you don't need bigger precision than 1s you should be fine. 
Hmm those mutation tests are failing because you added new methods and old ones are now not covered which means MSI score is not 100% anymore. 

Could you maybe try to use [@infection-ignore-all](https://infection.github.io/guide/usage.html#infection-ignore-all-support) above those all methods to see if this will make it happy? Another way around would be to keep in tests old methods as they internally use new ones and switch while migrating to 2.0

**Comment by christian-kolb** [comment]
I've updated it, but don't know what information I can get out of the report. Can you help me here?

**Comment by norberttech** [comment]
Yeah, I see it didn't help. 
In general, if you never used infection I recommend you to go through their readme but in this case, you can also simply reduce the MSI score in the infection.json file to 99 so I can merge it and tackle those mutants later as they are harmless in this case.

**Comment by christian-kolb** [comment]
I would like to dive deeper into the topic first. So for now I reduced the score to 99. Thanks for your help 🙂

**Comment by norberttech** [comment]
Thanks @christian-kolb this was truly needed contribution! 
I will tag the new release once I resolve this MSI issue

**Comment by christian-kolb** [comment]
Awesome, thanks for your help 🙂

**Comment by norberttech** [comment]
@christian-kolb https://github.com/aeon-php/calendar/releases done 👍

**Comment by christian-kolb** [comment]
@norberttech That was quick, thanks a lot for your help on this 🙂

**Pull request merged**
